<?php
declare(strict_types=1);
use FeedMySheep\Auth;use FeedMySheep\Database;use FeedMySheep\HttpRequest;use FeedMySheep\JsonResponse;use FeedMySheep\Session;use FeedMySheep\Validator;
$app=require dirname(__DIR__,2).'/src/bootstrap.php';Session::start();$pdo=(new Database($app['config']))->connection();$public=(new Auth($pdo))->requireUser()['id'];$q=$pdo->prepare('SELECT id FROM users WHERE public_id=?');$q->execute([$public]);$uid=(int)$q->fetchColumn();
$translation=strtoupper(trim($_GET['translation']??''));$book=strtoupper(trim($_GET['book']??''));$chapter=filter_var($_GET['chapter']??null,FILTER_VALIDATE_INT);$lookup=$pdo->prepare('SELECT t.id translation_id,b.id book_id FROM translations t JOIN translation_books tb ON tb.translation_id=t.id JOIN books b ON b.id=tb.book_id WHERE t.code=? AND b.code=?');$lookup->execute([$translation,$book]);$ids=$lookup->fetch();if(!$ids||$chapter===false)JsonResponse::error('validation_failed','Choose a valid translation, book, and chapter.',422);
if(($_SERVER['REQUEST_METHOD']??'GET')==='GET'){$h=$pdo->prepare('SELECT start_verse,end_verse,color FROM highlights WHERE user_id=? AND translation_id=? AND book_id=? AND chapter=?');$h->execute([$uid,$ids['translation_id'],$ids['book_id'],$chapter]);$b=$pdo->prepare('SELECT verse,label FROM bookmarks WHERE user_id=? AND translation_id=? AND book_id=? AND chapter=?');$b->execute([$uid,$ids['translation_id'],$ids['book_id'],$chapter]);$n=$pdo->prepare('SELECT id,start_verse,end_verse,body,updated_at FROM private_notes WHERE user_id=? AND book_id=? AND start_chapter=? ORDER BY start_verse');$n->execute([$uid,$ids['book_id'],$chapter]);JsonResponse::success(['highlights'=>$h->fetchAll(),'bookmarks'=>$b->fetchAll(),'notes'=>$n->fetchAll()]);}
HttpRequest::requireMethod('POST');Session::requireCsrf();$input=HttpRequest::json();$kind=$input['kind']??'';$start=filter_var($input['start_verse']??null,FILTER_VALIDATE_INT);$end=filter_var($input['end_verse']??$start,FILTER_VALIDATE_INT);if($start===false||$end===false||$start<1||$end<$start)JsonResponse::error('validation_failed','Select a valid verse range.',422);
if($kind==='highlight'){$s=$pdo->prepare("INSERT INTO highlights(user_id,translation_id,book_id,chapter,start_verse,end_verse,color) VALUES(?,?,?,?,?,?,'gold') ON DUPLICATE KEY UPDATE color=VALUES(color)");$s->execute([$uid,$ids['translation_id'],$ids['book_id'],$chapter,$start,$end]);}
elseif($kind==='bookmark'){$s=$pdo->prepare('INSERT INTO bookmarks(user_id,translation_id,book_id,chapter,verse) VALUES(?,?,?,?,?) ON DUPLICATE KEY UPDATE created_at=created_at');$s->execute([$uid,$ids['translation_id'],$ids['book_id'],$chapter,$start]);}
elseif($kind==='note'){$body=Validator::string($input['body']??null,1,5000);if($body===null)JsonResponse::error('validation_failed','Write a note of up to 5,000 characters.',422);$s=$pdo->prepare('INSERT INTO private_notes(user_id,book_id,start_chapter,start_verse,end_chapter,end_verse,body) VALUES(?,?,?,?,?,?,?)');$s->execute([$uid,$ids['book_id'],$chapter,$start,$chapter,$end,$body]);}
else JsonResponse::error('validation_failed','Unknown annotation type.',422);JsonResponse::success(['saved'=>true],201);
