import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';

const groups=await readFile(new URL('../assets/js/groups.js',import.meta.url),'utf8');
const index=await readFile(new URL('../index.html',import.meta.url),'utf8');
const auth=await readFile(new URL('../assets/js/auth.js',import.meta.url),'utf8');
const service=await readFile(new URL('../src/GroupService.php',import.meta.url),'utf8');
const schema=await readFile(new URL('../database/schema.sql',import.meta.url),'utf8');
const migration=await readFile(new URL('../database/migrations/010_permanent_group_codes.sql',import.meta.url),'utf8');
const inviteApi=await readFile(new URL('../api/groups/invite.php',import.meta.url),'utf8');
const joinApi=await readFile(new URL('../api/groups/join.php',import.meta.url),'utf8');
assert.match(groups,/new URLSearchParams\(location\.search\)\.get\('invite'\)/);
assert.match(groups,/url\.searchParams\.set\('invite', invite\.code\)/);
assert.match(groups,/url\.hash = 'group'/);
assert.match(groups,/\[data-invite-code\]'\)\.value = invite\.code/);
assert.match(groups,/navigator\.clipboard\.writeText\(document\.querySelector\('\[data-invite-code\]'\)\.value\)/);
assert.match(index,/data-invite-code/);
assert.match(index,/data-copy-code>Copy code/);
assert.match(index,/data-create-invite>Show sharing details/);
assert.doesNotMatch(groups,/expires_in_days/);
assert.match(service,/for \(\$i = 0; \$i < 4; \$i\+\+\)/);
assert.match(service,/FROM groups g WHERE g\.join_code_hash = :hash AND g\.archived_at IS NULL/);
assert.doesNotMatch(service,/INSERT INTO group_invites/);
assert.match(schema,/join_code CHAR\(4\) NOT NULL/);
assert.match(schema,/UNIQUE KEY uq_groups_join_code_hash \(join_code_hash\)/);
assert.match(migration,/WHERE join_code IS NULL/);
assert.match(migration,/IF NOT EXISTS \(SELECT 1 FROM groups WHERE join_code = candidate\)/);
assert.match(inviteApi,/createInvite\(\$id, \$userId\)/);
assert.match(joinApi,/hit\('join_group', HttpRequest::clientKey\(\), 10, 900\)/);
assert.match(auth,/if \(!localStorage\.getItem\('feedMySheep\.pendingInvite'\)\)/);
console.log('invite link tests passed');
