<?php
declare(strict_types=1);
use FeedMySheep\HttpRequest;
use FeedMySheep\JsonResponse;
use FeedMySheep\RateLimiter;
use FeedMySheep\Session;
use FeedMySheep\Validator;
use FeedMySheep\Auth;
require __DIR__ . '/_init.php';
HttpRequest::requireMethod('POST');
Session::requireCsrf();
$input = HttpRequest::json();
$username = Validator::username($input['username'] ?? null);
$password = is_string($input['password'] ?? null) ? $input['password'] : '';
if ($username === null || $password === '') JsonResponse::error('validation_failed', 'Enter a valid username and password.', 422);
$pdo = $database->connection();
$auth = new Auth($pdo);
(new RateLimiter($pdo))->hit('login', HttpRequest::clientKey() . ':' . $username, 8, 900);
$user = $auth->attempt($username, $password);
if ($user === null) JsonResponse::error('invalid_credentials', 'The username or password is incorrect.', 401);
$lookup = $pdo->prepare('SELECT id FROM users WHERE public_id = :public_id');
$lookup->execute(['public_id' => $user['id']]);
Session::login((int) $lookup->fetchColumn());
JsonResponse::success(['user' => $user, 'csrf_token' => Session::csrfToken()]);
