#!/usr/bin/env node
/**
 * Copies the notification icon into the Android project.
 *
 * `android/` is generated by `npx cap add android` and is not committed, so
 * anything hand-placed inside it disappears the moment the project is recreated
 * on another machine. Keeping the source in mobile/resources and copying it as
 * part of every sync means a fresh clone produces the same build.
 *
 * Android draws only the alpha channel of a notification icon, tinted with the
 * iconColor from capacitor.config.json. Leaving it out makes Android fall back
 * to the launcher icon, which is a full-colour square and renders as a white
 * blob in the status bar.
 */
import { cp, mkdir, readdir } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const MOBILE_DIR = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const SOURCE = join(MOBILE_DIR, 'resources', 'notification');
const RES = join(MOBILE_DIR, 'android', 'app', 'src', 'main', 'res');

if (!existsSync(RES)) {
  console.log('android-extras: no Android project yet, skipping. Run `npx cap add android` first.');
  process.exit(0);
}
if (!existsSync(SOURCE)) {
  console.error(`android-extras: expected notification icons at ${SOURCE}`);
  process.exit(1);
}

let copied = 0;
for (const density of await readdir(SOURCE)) {
  const target = join(RES, density);
  await mkdir(target, { recursive: true });
  for (const file of await readdir(join(SOURCE, density))) {
    await cp(join(SOURCE, density, file), join(target, file));
    copied++;
  }
}
console.log(`android-extras: installed ${copied} notification icon files`);
