-- Catholic canon and approved public-domain Douay-Rheims source metadata.
-- Text is not bundled; import only the verified engDRA source package.
START TRANSACTION;
INSERT INTO canons (code, name, book_count, is_default) VALUES ('catholic-73', 'Catholic Canon', 73, TRUE) ON DUPLICATE KEY UPDATE name=VALUES(name), book_count=73, is_default=TRUE;
INSERT INTO books (code,name,testament) VALUES ('GEN','Genesis','old') ON DUPLICATE KEY UPDATE name=VALUES(name), testament=VALUES(testament);
INSERT INTO canon_books (canon_id,book_id,position,chapter_count) SELECT c.id,b.id,1,50 FROM canons c JOIN books b ON b.code='GEN' WHERE c.code='catholic-73' ON DUPLICATE KEY UPDATE position=VALUES(position),chapter_count=VALUES(chapter_count);
INSERT INTO book_names (book_id,locale,name,is_primary) SELECT id,'en','Genesis',TRUE FROM books WHERE code='GEN' ON DUPLICATE KEY UPDATE book_id=VALUES(book_id),is_primary=VALUES(is_primary);
INSERT INTO books (code,name,testament) VALUES ('EXO','Exodus','old') ON DUPLICATE KEY UPDATE name=VALUES(name), testament=VALUES(testament);
INSERT INTO canon_books (canon_id,book_id,position,chapter_count) SELECT c.id,b.id,2,40 FROM canons c JOIN books b ON b.code='EXO' WHERE c.code='catholic-73' ON DUPLICATE KEY UPDATE position=VALUES(position),chapter_count=VALUES(chapter_count);
INSERT INTO book_names (book_id,locale,name,is_primary) SELECT id,'en','Exodus',TRUE FROM books WHERE code='EXO' ON DUPLICATE KEY UPDATE book_id=VALUES(book_id),is_primary=VALUES(is_primary);
INSERT INTO books (code,name,testament) VALUES ('LEV','Leviticus','old') ON DUPLICATE KEY UPDATE name=VALUES(name), testament=VALUES(testament);
INSERT INTO canon_books (canon_id,book_id,position,chapter_count) SELECT c.id,b.id,3,27 FROM canons c JOIN books b ON b.code='LEV' WHERE c.code='catholic-73' ON DUPLICATE KEY UPDATE position=VALUES(position),chapter_count=VALUES(chapter_count);
INSERT INTO book_names (book_id,locale,name,is_primary) SELECT id,'en','Leviticus',TRUE FROM books WHERE code='LEV' ON DUPLICATE KEY UPDATE book_id=VALUES(book_id),is_primary=VALUES(is_primary);
INSERT INTO books (code,name,testament) VALUES ('NUM','Numbers','old') ON DUPLICATE KEY UPDATE name=VALUES(name), testament=VALUES(testament);
INSERT INTO canon_books (canon_id,book_id,position,chapter_count) SELECT c.id,b.id,4,36 FROM canons c JOIN books b ON b.code='NUM' WHERE c.code='catholic-73' ON DUPLICATE KEY UPDATE position=VALUES(position),chapter_count=VALUES(chapter_count);
INSERT INTO book_names (book_id,locale,name,is_primary) SELECT id,'en','Numbers',TRUE FROM books WHERE code='NUM' ON DUPLICATE KEY UPDATE book_id=VALUES(book_id),is_primary=VALUES(is_primary);
INSERT INTO books (code,name,testament) VALUES ('DEU','Deuteronomy','old') ON DUPLICATE KEY UPDATE name=VALUES(name), testament=VALUES(testament);
INSERT INTO canon_books (canon_id,book_id,position,chapter_count) SELECT c.id,b.id,5,34 FROM canons c JOIN books b ON b.code='DEU' WHERE c.code='catholic-73' ON DUPLICATE KEY UPDATE position=VALUES(position),chapter_count=VALUES(chapter_count);
INSERT INTO book_names (book_id,locale,name,is_primary) SELECT id,'en','Deuteronomy',TRUE FROM books WHERE code='DEU' ON DUPLICATE KEY UPDATE book_id=VALUES(book_id),is_primary=VALUES(is_primary);
INSERT INTO books (code,name,testament) VALUES ('JOS','Joshua','old') ON DUPLICATE KEY UPDATE name=VALUES(name), testament=VALUES(testament);
INSERT INTO canon_books (canon_id,book_id,position,chapter_count) SELECT c.id,b.id,6,24 FROM canons c JOIN books b ON b.code='JOS' WHERE c.code='catholic-73' ON DUPLICATE KEY UPDATE position=VALUES(position),chapter_count=VALUES(chapter_count);
INSERT INTO book_names (book_id,locale,name,is_primary) SELECT id,'en','Joshua',TRUE FROM books WHERE code='JOS' ON DUPLICATE KEY UPDATE book_id=VALUES(book_id),is_primary=VALUES(is_primary);
INSERT INTO books (code,name,testament) VALUES ('JDG','Judges','old') ON DUPLICATE KEY UPDATE name=VALUES(name), testament=VALUES(testament);
INSERT INTO canon_books (canon_id,book_id,position,chapter_count) SELECT c.id,b.id,7,21 FROM canons c JOIN books b ON b.code='JDG' WHERE c.code='catholic-73' ON DUPLICATE KEY UPDATE position=VALUES(position),chapter_count=VALUES(chapter_count);
INSERT INTO book_names (book_id,locale,name,is_primary) SELECT id,'en','Judges',TRUE FROM books WHERE code='JDG' ON DUPLICATE KEY UPDATE book_id=VALUES(book_id),is_primary=VALUES(is_primary);
INSERT INTO books (code,name,testament) VALUES ('RUT','Ruth','old') ON DUPLICATE KEY UPDATE name=VALUES(name), testament=VALUES(testament);
INSERT INTO canon_books (canon_id,book_id,position,chapter_count) SELECT c.id,b.id,8,4 FROM canons c JOIN books b ON b.code='RUT' WHERE c.code='catholic-73' ON DUPLICATE KEY UPDATE position=VALUES(position),chapter_count=VALUES(chapter_count);
INSERT INTO book_names (book_id,locale,name,is_primary) SELECT id,'en','Ruth',TRUE FROM books WHERE code='RUT' ON DUPLICATE KEY UPDATE book_id=VALUES(book_id),is_primary=VALUES(is_primary);
INSERT INTO books (code,name,testament) VALUES ('1SA','1 Samuel','old') ON DUPLICATE KEY UPDATE name=VALUES(name), testament=VALUES(testament);
INSERT INTO canon_books (canon_id,book_id,position,chapter_count) SELECT c.id,b.id,9,31 FROM canons c JOIN books b ON b.code='1SA' WHERE c.code='catholic-73' ON DUPLICATE KEY UPDATE position=VALUES(position),chapter_count=VALUES(chapter_count);
INSERT INTO book_names (book_id,locale,name,is_primary) SELECT id,'en','1 Samuel',TRUE FROM books WHERE code='1SA' ON DUPLICATE KEY UPDATE book_id=VALUES(book_id),is_primary=VALUES(is_primary);
INSERT INTO book_names (book_id,locale,name,is_primary) SELECT id,'en','1 Kings (Douay)',FALSE FROM books WHERE code='1SA' ON DUPLICATE KEY UPDATE book_id=VALUES(book_id),is_primary=VALUES(is_primary);
INSERT INTO books (code,name,testament) VALUES ('2SA','2 Samuel','old') ON DUPLICATE KEY UPDATE name=VALUES(name), testament=VALUES(testament);
INSERT INTO canon_books (canon_id,book_id,position,chapter_count) SELECT c.id,b.id,10,24 FROM canons c JOIN books b ON b.code='2SA' WHERE c.code='catholic-73' ON DUPLICATE KEY UPDATE position=VALUES(position),chapter_count=VALUES(chapter_count);
INSERT INTO book_names (book_id,locale,name,is_primary) SELECT id,'en','2 Samuel',TRUE FROM books WHERE code='2SA' ON DUPLICATE KEY UPDATE book_id=VALUES(book_id),is_primary=VALUES(is_primary);
INSERT INTO book_names (book_id,locale,name,is_primary) SELECT id,'en','2 Kings (Douay)',FALSE FROM books WHERE code='2SA' ON DUPLICATE KEY UPDATE book_id=VALUES(book_id),is_primary=VALUES(is_primary);
INSERT INTO books (code,name,testament) VALUES ('1KI','1 Kings','old') ON DUPLICATE KEY UPDATE name=VALUES(name), testament=VALUES(testament);
INSERT INTO canon_books (canon_id,book_id,position,chapter_count) SELECT c.id,b.id,11,22 FROM canons c JOIN books b ON b.code='1KI' WHERE c.code='catholic-73' ON DUPLICATE KEY UPDATE position=VALUES(position),chapter_count=VALUES(chapter_count);
INSERT INTO book_names (book_id,locale,name,is_primary) SELECT id,'en','1 Kings',TRUE FROM books WHERE code='1KI' ON DUPLICATE KEY UPDATE book_id=VALUES(book_id),is_primary=VALUES(is_primary);
INSERT INTO book_names (book_id,locale,name,is_primary) SELECT id,'en','3 Kings (Douay)',FALSE FROM books WHERE code='1KI' ON DUPLICATE KEY UPDATE book_id=VALUES(book_id),is_primary=VALUES(is_primary);
INSERT INTO books (code,name,testament) VALUES ('2KI','2 Kings','old') ON DUPLICATE KEY UPDATE name=VALUES(name), testament=VALUES(testament);
INSERT INTO canon_books (canon_id,book_id,position,chapter_count) SELECT c.id,b.id,12,25 FROM canons c JOIN books b ON b.code='2KI' WHERE c.code='catholic-73' ON DUPLICATE KEY UPDATE position=VALUES(position),chapter_count=VALUES(chapter_count);
INSERT INTO book_names (book_id,locale,name,is_primary) SELECT id,'en','2 Kings',TRUE FROM books WHERE code='2KI' ON DUPLICATE KEY UPDATE book_id=VALUES(book_id),is_primary=VALUES(is_primary);
INSERT INTO book_names (book_id,locale,name,is_primary) SELECT id,'en','4 Kings (Douay)',FALSE FROM books WHERE code='2KI' ON DUPLICATE KEY UPDATE book_id=VALUES(book_id),is_primary=VALUES(is_primary);
INSERT INTO books (code,name,testament) VALUES ('1CH','1 Chronicles','old') ON DUPLICATE KEY UPDATE name=VALUES(name), testament=VALUES(testament);
INSERT INTO canon_books (canon_id,book_id,position,chapter_count) SELECT c.id,b.id,13,29 FROM canons c JOIN books b ON b.code='1CH' WHERE c.code='catholic-73' ON DUPLICATE KEY UPDATE position=VALUES(position),chapter_count=VALUES(chapter_count);
INSERT INTO book_names (book_id,locale,name,is_primary) SELECT id,'en','1 Chronicles',TRUE FROM books WHERE code='1CH' ON DUPLICATE KEY UPDATE book_id=VALUES(book_id),is_primary=VALUES(is_primary);
INSERT INTO books (code,name,testament) VALUES ('2CH','2 Chronicles','old') ON DUPLICATE KEY UPDATE name=VALUES(name), testament=VALUES(testament);
INSERT INTO canon_books (canon_id,book_id,position,chapter_count) SELECT c.id,b.id,14,36 FROM canons c JOIN books b ON b.code='2CH' WHERE c.code='catholic-73' ON DUPLICATE KEY UPDATE position=VALUES(position),chapter_count=VALUES(chapter_count);
INSERT INTO book_names (book_id,locale,name,is_primary) SELECT id,'en','2 Chronicles',TRUE FROM books WHERE code='2CH' ON DUPLICATE KEY UPDATE book_id=VALUES(book_id),is_primary=VALUES(is_primary);
INSERT INTO books (code,name,testament) VALUES ('EZR','Ezra','old') ON DUPLICATE KEY UPDATE name=VALUES(name), testament=VALUES(testament);
INSERT INTO canon_books (canon_id,book_id,position,chapter_count) SELECT c.id,b.id,15,10 FROM canons c JOIN books b ON b.code='EZR' WHERE c.code='catholic-73' ON DUPLICATE KEY UPDATE position=VALUES(position),chapter_count=VALUES(chapter_count);
INSERT INTO book_names (book_id,locale,name,is_primary) SELECT id,'en','Ezra',TRUE FROM books WHERE code='EZR' ON DUPLICATE KEY UPDATE book_id=VALUES(book_id),is_primary=VALUES(is_primary);
INSERT INTO book_names (book_id,locale,name,is_primary) SELECT id,'en','1 Esdras',FALSE FROM books WHERE code='EZR' ON DUPLICATE KEY UPDATE book_id=VALUES(book_id),is_primary=VALUES(is_primary);
INSERT INTO books (code,name,testament) VALUES ('NEH','Nehemiah','old') ON DUPLICATE KEY UPDATE name=VALUES(name), testament=VALUES(testament);
INSERT INTO canon_books (canon_id,book_id,position,chapter_count) SELECT c.id,b.id,16,13 FROM canons c JOIN books b ON b.code='NEH' WHERE c.code='catholic-73' ON DUPLICATE KEY UPDATE position=VALUES(position),chapter_count=VALUES(chapter_count);
INSERT INTO book_names (book_id,locale,name,is_primary) SELECT id,'en','Nehemiah',TRUE FROM books WHERE code='NEH' ON DUPLICATE KEY UPDATE book_id=VALUES(book_id),is_primary=VALUES(is_primary);
INSERT INTO book_names (book_id,locale,name,is_primary) SELECT id,'en','2 Esdras',FALSE FROM books WHERE code='NEH' ON DUPLICATE KEY UPDATE book_id=VALUES(book_id),is_primary=VALUES(is_primary);
INSERT INTO books (code,name,testament) VALUES ('TOB','Tobit','old') ON DUPLICATE KEY UPDATE name=VALUES(name), testament=VALUES(testament);
INSERT INTO canon_books (canon_id,book_id,position,chapter_count) SELECT c.id,b.id,17,14 FROM canons c JOIN books b ON b.code='TOB' WHERE c.code='catholic-73' ON DUPLICATE KEY UPDATE position=VALUES(position),chapter_count=VALUES(chapter_count);
INSERT INTO book_names (book_id,locale,name,is_primary) SELECT id,'en','Tobit',TRUE FROM books WHERE code='TOB' ON DUPLICATE KEY UPDATE book_id=VALUES(book_id),is_primary=VALUES(is_primary);
INSERT INTO books (code,name,testament) VALUES ('JDT','Judith','old') ON DUPLICATE KEY UPDATE name=VALUES(name), testament=VALUES(testament);
INSERT INTO canon_books (canon_id,book_id,position,chapter_count) SELECT c.id,b.id,18,16 FROM canons c JOIN books b ON b.code='JDT' WHERE c.code='catholic-73' ON DUPLICATE KEY UPDATE position=VALUES(position),chapter_count=VALUES(chapter_count);
INSERT INTO book_names (book_id,locale,name,is_primary) SELECT id,'en','Judith',TRUE FROM books WHERE code='JDT' ON DUPLICATE KEY UPDATE book_id=VALUES(book_id),is_primary=VALUES(is_primary);
INSERT INTO books (code,name,testament) VALUES ('EST','Esther','old') ON DUPLICATE KEY UPDATE name=VALUES(name), testament=VALUES(testament);
INSERT INTO canon_books (canon_id,book_id,position,chapter_count) SELECT c.id,b.id,19,16 FROM canons c JOIN books b ON b.code='EST' WHERE c.code='catholic-73' ON DUPLICATE KEY UPDATE position=VALUES(position),chapter_count=VALUES(chapter_count);
INSERT INTO book_names (book_id,locale,name,is_primary) SELECT id,'en','Esther',TRUE FROM books WHERE code='EST' ON DUPLICATE KEY UPDATE book_id=VALUES(book_id),is_primary=VALUES(is_primary);
INSERT INTO books (code,name,testament) VALUES ('1MA','1 Maccabees','old') ON DUPLICATE KEY UPDATE name=VALUES(name), testament=VALUES(testament);
INSERT INTO canon_books (canon_id,book_id,position,chapter_count) SELECT c.id,b.id,20,16 FROM canons c JOIN books b ON b.code='1MA' WHERE c.code='catholic-73' ON DUPLICATE KEY UPDATE position=VALUES(position),chapter_count=VALUES(chapter_count);
INSERT INTO book_names (book_id,locale,name,is_primary) SELECT id,'en','1 Maccabees',TRUE FROM books WHERE code='1MA' ON DUPLICATE KEY UPDATE book_id=VALUES(book_id),is_primary=VALUES(is_primary);
INSERT INTO books (code,name,testament) VALUES ('2MA','2 Maccabees','old') ON DUPLICATE KEY UPDATE name=VALUES(name), testament=VALUES(testament);
INSERT INTO canon_books (canon_id,book_id,position,chapter_count) SELECT c.id,b.id,21,15 FROM canons c JOIN books b ON b.code='2MA' WHERE c.code='catholic-73' ON DUPLICATE KEY UPDATE position=VALUES(position),chapter_count=VALUES(chapter_count);
INSERT INTO book_names (book_id,locale,name,is_primary) SELECT id,'en','2 Maccabees',TRUE FROM books WHERE code='2MA' ON DUPLICATE KEY UPDATE book_id=VALUES(book_id),is_primary=VALUES(is_primary);
INSERT INTO books (code,name,testament) VALUES ('JOB','Job','old') ON DUPLICATE KEY UPDATE name=VALUES(name), testament=VALUES(testament);
INSERT INTO canon_books (canon_id,book_id,position,chapter_count) SELECT c.id,b.id,22,42 FROM canons c JOIN books b ON b.code='JOB' WHERE c.code='catholic-73' ON DUPLICATE KEY UPDATE position=VALUES(position),chapter_count=VALUES(chapter_count);
INSERT INTO book_names (book_id,locale,name,is_primary) SELECT id,'en','Job',TRUE FROM books WHERE code='JOB' ON DUPLICATE KEY UPDATE book_id=VALUES(book_id),is_primary=VALUES(is_primary);
INSERT INTO books (code,name,testament) VALUES ('PSA','Psalms','old') ON DUPLICATE KEY UPDATE name=VALUES(name), testament=VALUES(testament);
INSERT INTO canon_books (canon_id,book_id,position,chapter_count) SELECT c.id,b.id,23,150 FROM canons c JOIN books b ON b.code='PSA' WHERE c.code='catholic-73' ON DUPLICATE KEY UPDATE position=VALUES(position),chapter_count=VALUES(chapter_count);
INSERT INTO book_names (book_id,locale,name,is_primary) SELECT id,'en','Psalms',TRUE FROM books WHERE code='PSA' ON DUPLICATE KEY UPDATE book_id=VALUES(book_id),is_primary=VALUES(is_primary);
INSERT INTO book_names (book_id,locale,name,is_primary) SELECT id,'en','Psalm',FALSE FROM books WHERE code='PSA' ON DUPLICATE KEY UPDATE book_id=VALUES(book_id),is_primary=VALUES(is_primary);
INSERT INTO book_names (book_id,locale,name,is_primary) SELECT id,'en','Psalms',TRUE FROM books WHERE code='PSA' ON DUPLICATE KEY UPDATE book_id=VALUES(book_id),is_primary=VALUES(is_primary);
INSERT INTO books (code,name,testament) VALUES ('PRO','Proverbs','old') ON DUPLICATE KEY UPDATE name=VALUES(name), testament=VALUES(testament);
INSERT INTO canon_books (canon_id,book_id,position,chapter_count) SELECT c.id,b.id,24,31 FROM canons c JOIN books b ON b.code='PRO' WHERE c.code='catholic-73' ON DUPLICATE KEY UPDATE position=VALUES(position),chapter_count=VALUES(chapter_count);
INSERT INTO book_names (book_id,locale,name,is_primary) SELECT id,'en','Proverbs',TRUE FROM books WHERE code='PRO' ON DUPLICATE KEY UPDATE book_id=VALUES(book_id),is_primary=VALUES(is_primary);
INSERT INTO books (code,name,testament) VALUES ('ECC','Ecclesiastes','old') ON DUPLICATE KEY UPDATE name=VALUES(name), testament=VALUES(testament);
INSERT INTO canon_books (canon_id,book_id,position,chapter_count) SELECT c.id,b.id,25,12 FROM canons c JOIN books b ON b.code='ECC' WHERE c.code='catholic-73' ON DUPLICATE KEY UPDATE position=VALUES(position),chapter_count=VALUES(chapter_count);
INSERT INTO book_names (book_id,locale,name,is_primary) SELECT id,'en','Ecclesiastes',TRUE FROM books WHERE code='ECC' ON DUPLICATE KEY UPDATE book_id=VALUES(book_id),is_primary=VALUES(is_primary);
INSERT INTO books (code,name,testament) VALUES ('SNG','Song of Songs','old') ON DUPLICATE KEY UPDATE name=VALUES(name), testament=VALUES(testament);
INSERT INTO canon_books (canon_id,book_id,position,chapter_count) SELECT c.id,b.id,26,8 FROM canons c JOIN books b ON b.code='SNG' WHERE c.code='catholic-73' ON DUPLICATE KEY UPDATE position=VALUES(position),chapter_count=VALUES(chapter_count);
INSERT INTO book_names (book_id,locale,name,is_primary) SELECT id,'en','Song of Songs',TRUE FROM books WHERE code='SNG' ON DUPLICATE KEY UPDATE book_id=VALUES(book_id),is_primary=VALUES(is_primary);
INSERT INTO book_names (book_id,locale,name,is_primary) SELECT id,'en','Song of Solomon',FALSE FROM books WHERE code='SNG' ON DUPLICATE KEY UPDATE book_id=VALUES(book_id),is_primary=VALUES(is_primary);
INSERT INTO book_names (book_id,locale,name,is_primary) SELECT id,'en','Canticle of Canticles',FALSE FROM books WHERE code='SNG' ON DUPLICATE KEY UPDATE book_id=VALUES(book_id),is_primary=VALUES(is_primary);
INSERT INTO book_names (book_id,locale,name,is_primary) SELECT id,'en','Canticles',FALSE FROM books WHERE code='SNG' ON DUPLICATE KEY UPDATE book_id=VALUES(book_id),is_primary=VALUES(is_primary);
INSERT INTO books (code,name,testament) VALUES ('WIS','Wisdom','old') ON DUPLICATE KEY UPDATE name=VALUES(name), testament=VALUES(testament);
INSERT INTO canon_books (canon_id,book_id,position,chapter_count) SELECT c.id,b.id,27,19 FROM canons c JOIN books b ON b.code='WIS' WHERE c.code='catholic-73' ON DUPLICATE KEY UPDATE position=VALUES(position),chapter_count=VALUES(chapter_count);
INSERT INTO book_names (book_id,locale,name,is_primary) SELECT id,'en','Wisdom',TRUE FROM books WHERE code='WIS' ON DUPLICATE KEY UPDATE book_id=VALUES(book_id),is_primary=VALUES(is_primary);
INSERT INTO books (code,name,testament) VALUES ('SIR','Sirach','old') ON DUPLICATE KEY UPDATE name=VALUES(name), testament=VALUES(testament);
INSERT INTO canon_books (canon_id,book_id,position,chapter_count) SELECT c.id,b.id,28,51 FROM canons c JOIN books b ON b.code='SIR' WHERE c.code='catholic-73' ON DUPLICATE KEY UPDATE position=VALUES(position),chapter_count=VALUES(chapter_count);
INSERT INTO book_names (book_id,locale,name,is_primary) SELECT id,'en','Sirach',TRUE FROM books WHERE code='SIR' ON DUPLICATE KEY UPDATE book_id=VALUES(book_id),is_primary=VALUES(is_primary);
INSERT INTO book_names (book_id,locale,name,is_primary) SELECT id,'en','Ecclesiasticus',FALSE FROM books WHERE code='SIR' ON DUPLICATE KEY UPDATE book_id=VALUES(book_id),is_primary=VALUES(is_primary);
INSERT INTO books (code,name,testament) VALUES ('ISA','Isaiah','old') ON DUPLICATE KEY UPDATE name=VALUES(name), testament=VALUES(testament);
INSERT INTO canon_books (canon_id,book_id,position,chapter_count) SELECT c.id,b.id,29,66 FROM canons c JOIN books b ON b.code='ISA' WHERE c.code='catholic-73' ON DUPLICATE KEY UPDATE position=VALUES(position),chapter_count=VALUES(chapter_count);
INSERT INTO book_names (book_id,locale,name,is_primary) SELECT id,'en','Isaiah',TRUE FROM books WHERE code='ISA' ON DUPLICATE KEY UPDATE book_id=VALUES(book_id),is_primary=VALUES(is_primary);
INSERT INTO books (code,name,testament) VALUES ('JER','Jeremiah','old') ON DUPLICATE KEY UPDATE name=VALUES(name), testament=VALUES(testament);
INSERT INTO canon_books (canon_id,book_id,position,chapter_count) SELECT c.id,b.id,30,52 FROM canons c JOIN books b ON b.code='JER' WHERE c.code='catholic-73' ON DUPLICATE KEY UPDATE position=VALUES(position),chapter_count=VALUES(chapter_count);
INSERT INTO book_names (book_id,locale,name,is_primary) SELECT id,'en','Jeremiah',TRUE FROM books WHERE code='JER' ON DUPLICATE KEY UPDATE book_id=VALUES(book_id),is_primary=VALUES(is_primary);
INSERT INTO books (code,name,testament) VALUES ('LAM','Lamentations','old') ON DUPLICATE KEY UPDATE name=VALUES(name), testament=VALUES(testament);
INSERT INTO canon_books (canon_id,book_id,position,chapter_count) SELECT c.id,b.id,31,5 FROM canons c JOIN books b ON b.code='LAM' WHERE c.code='catholic-73' ON DUPLICATE KEY UPDATE position=VALUES(position),chapter_count=VALUES(chapter_count);
INSERT INTO book_names (book_id,locale,name,is_primary) SELECT id,'en','Lamentations',TRUE FROM books WHERE code='LAM' ON DUPLICATE KEY UPDATE book_id=VALUES(book_id),is_primary=VALUES(is_primary);
INSERT INTO books (code,name,testament) VALUES ('BAR','Baruch','old') ON DUPLICATE KEY UPDATE name=VALUES(name), testament=VALUES(testament);
INSERT INTO canon_books (canon_id,book_id,position,chapter_count) SELECT c.id,b.id,32,6 FROM canons c JOIN books b ON b.code='BAR' WHERE c.code='catholic-73' ON DUPLICATE KEY UPDATE position=VALUES(position),chapter_count=VALUES(chapter_count);
INSERT INTO book_names (book_id,locale,name,is_primary) SELECT id,'en','Baruch',TRUE FROM books WHERE code='BAR' ON DUPLICATE KEY UPDATE book_id=VALUES(book_id),is_primary=VALUES(is_primary);
INSERT INTO books (code,name,testament) VALUES ('EZK','Ezekiel','old') ON DUPLICATE KEY UPDATE name=VALUES(name), testament=VALUES(testament);
INSERT INTO canon_books (canon_id,book_id,position,chapter_count) SELECT c.id,b.id,33,48 FROM canons c JOIN books b ON b.code='EZK' WHERE c.code='catholic-73' ON DUPLICATE KEY UPDATE position=VALUES(position),chapter_count=VALUES(chapter_count);
INSERT INTO book_names (book_id,locale,name,is_primary) SELECT id,'en','Ezekiel',TRUE FROM books WHERE code='EZK' ON DUPLICATE KEY UPDATE book_id=VALUES(book_id),is_primary=VALUES(is_primary);
INSERT INTO books (code,name,testament) VALUES ('DAN','Daniel','old') ON DUPLICATE KEY UPDATE name=VALUES(name), testament=VALUES(testament);
INSERT INTO canon_books (canon_id,book_id,position,chapter_count) SELECT c.id,b.id,34,14 FROM canons c JOIN books b ON b.code='DAN' WHERE c.code='catholic-73' ON DUPLICATE KEY UPDATE position=VALUES(position),chapter_count=VALUES(chapter_count);
INSERT INTO book_names (book_id,locale,name,is_primary) SELECT id,'en','Daniel',TRUE FROM books WHERE code='DAN' ON DUPLICATE KEY UPDATE book_id=VALUES(book_id),is_primary=VALUES(is_primary);
INSERT INTO books (code,name,testament) VALUES ('HOS','Hosea','old') ON DUPLICATE KEY UPDATE name=VALUES(name), testament=VALUES(testament);
INSERT INTO canon_books (canon_id,book_id,position,chapter_count) SELECT c.id,b.id,35,14 FROM canons c JOIN books b ON b.code='HOS' WHERE c.code='catholic-73' ON DUPLICATE KEY UPDATE position=VALUES(position),chapter_count=VALUES(chapter_count);
INSERT INTO book_names (book_id,locale,name,is_primary) SELECT id,'en','Hosea',TRUE FROM books WHERE code='HOS' ON DUPLICATE KEY UPDATE book_id=VALUES(book_id),is_primary=VALUES(is_primary);
INSERT INTO books (code,name,testament) VALUES ('JOL','Joel','old') ON DUPLICATE KEY UPDATE name=VALUES(name), testament=VALUES(testament);
INSERT INTO canon_books (canon_id,book_id,position,chapter_count) SELECT c.id,b.id,36,3 FROM canons c JOIN books b ON b.code='JOL' WHERE c.code='catholic-73' ON DUPLICATE KEY UPDATE position=VALUES(position),chapter_count=VALUES(chapter_count);
INSERT INTO book_names (book_id,locale,name,is_primary) SELECT id,'en','Joel',TRUE FROM books WHERE code='JOL' ON DUPLICATE KEY UPDATE book_id=VALUES(book_id),is_primary=VALUES(is_primary);
INSERT INTO books (code,name,testament) VALUES ('AMO','Amos','old') ON DUPLICATE KEY UPDATE name=VALUES(name), testament=VALUES(testament);
INSERT INTO canon_books (canon_id,book_id,position,chapter_count) SELECT c.id,b.id,37,9 FROM canons c JOIN books b ON b.code='AMO' WHERE c.code='catholic-73' ON DUPLICATE KEY UPDATE position=VALUES(position),chapter_count=VALUES(chapter_count);
INSERT INTO book_names (book_id,locale,name,is_primary) SELECT id,'en','Amos',TRUE FROM books WHERE code='AMO' ON DUPLICATE KEY UPDATE book_id=VALUES(book_id),is_primary=VALUES(is_primary);
INSERT INTO books (code,name,testament) VALUES ('OBA','Obadiah','old') ON DUPLICATE KEY UPDATE name=VALUES(name), testament=VALUES(testament);
INSERT INTO canon_books (canon_id,book_id,position,chapter_count) SELECT c.id,b.id,38,1 FROM canons c JOIN books b ON b.code='OBA' WHERE c.code='catholic-73' ON DUPLICATE KEY UPDATE position=VALUES(position),chapter_count=VALUES(chapter_count);
INSERT INTO book_names (book_id,locale,name,is_primary) SELECT id,'en','Obadiah',TRUE FROM books WHERE code='OBA' ON DUPLICATE KEY UPDATE book_id=VALUES(book_id),is_primary=VALUES(is_primary);
INSERT INTO books (code,name,testament) VALUES ('JON','Jonah','old') ON DUPLICATE KEY UPDATE name=VALUES(name), testament=VALUES(testament);
INSERT INTO canon_books (canon_id,book_id,position,chapter_count) SELECT c.id,b.id,39,4 FROM canons c JOIN books b ON b.code='JON' WHERE c.code='catholic-73' ON DUPLICATE KEY UPDATE position=VALUES(position),chapter_count=VALUES(chapter_count);
INSERT INTO book_names (book_id,locale,name,is_primary) SELECT id,'en','Jonah',TRUE FROM books WHERE code='JON' ON DUPLICATE KEY UPDATE book_id=VALUES(book_id),is_primary=VALUES(is_primary);
INSERT INTO books (code,name,testament) VALUES ('MIC','Micah','old') ON DUPLICATE KEY UPDATE name=VALUES(name), testament=VALUES(testament);
INSERT INTO canon_books (canon_id,book_id,position,chapter_count) SELECT c.id,b.id,40,7 FROM canons c JOIN books b ON b.code='MIC' WHERE c.code='catholic-73' ON DUPLICATE KEY UPDATE position=VALUES(position),chapter_count=VALUES(chapter_count);
INSERT INTO book_names (book_id,locale,name,is_primary) SELECT id,'en','Micah',TRUE FROM books WHERE code='MIC' ON DUPLICATE KEY UPDATE book_id=VALUES(book_id),is_primary=VALUES(is_primary);
INSERT INTO books (code,name,testament) VALUES ('NAM','Nahum','old') ON DUPLICATE KEY UPDATE name=VALUES(name), testament=VALUES(testament);
INSERT INTO canon_books (canon_id,book_id,position,chapter_count) SELECT c.id,b.id,41,3 FROM canons c JOIN books b ON b.code='NAM' WHERE c.code='catholic-73' ON DUPLICATE KEY UPDATE position=VALUES(position),chapter_count=VALUES(chapter_count);
INSERT INTO book_names (book_id,locale,name,is_primary) SELECT id,'en','Nahum',TRUE FROM books WHERE code='NAM' ON DUPLICATE KEY UPDATE book_id=VALUES(book_id),is_primary=VALUES(is_primary);
INSERT INTO books (code,name,testament) VALUES ('HAB','Habakkuk','old') ON DUPLICATE KEY UPDATE name=VALUES(name), testament=VALUES(testament);
INSERT INTO canon_books (canon_id,book_id,position,chapter_count) SELECT c.id,b.id,42,3 FROM canons c JOIN books b ON b.code='HAB' WHERE c.code='catholic-73' ON DUPLICATE KEY UPDATE position=VALUES(position),chapter_count=VALUES(chapter_count);
INSERT INTO book_names (book_id,locale,name,is_primary) SELECT id,'en','Habakkuk',TRUE FROM books WHERE code='HAB' ON DUPLICATE KEY UPDATE book_id=VALUES(book_id),is_primary=VALUES(is_primary);
INSERT INTO books (code,name,testament) VALUES ('ZEP','Zephaniah','old') ON DUPLICATE KEY UPDATE name=VALUES(name), testament=VALUES(testament);
INSERT INTO canon_books (canon_id,book_id,position,chapter_count) SELECT c.id,b.id,43,3 FROM canons c JOIN books b ON b.code='ZEP' WHERE c.code='catholic-73' ON DUPLICATE KEY UPDATE position=VALUES(position),chapter_count=VALUES(chapter_count);
INSERT INTO book_names (book_id,locale,name,is_primary) SELECT id,'en','Zephaniah',TRUE FROM books WHERE code='ZEP' ON DUPLICATE KEY UPDATE book_id=VALUES(book_id),is_primary=VALUES(is_primary);
INSERT INTO books (code,name,testament) VALUES ('HAG','Haggai','old') ON DUPLICATE KEY UPDATE name=VALUES(name), testament=VALUES(testament);
INSERT INTO canon_books (canon_id,book_id,position,chapter_count) SELECT c.id,b.id,44,2 FROM canons c JOIN books b ON b.code='HAG' WHERE c.code='catholic-73' ON DUPLICATE KEY UPDATE position=VALUES(position),chapter_count=VALUES(chapter_count);
INSERT INTO book_names (book_id,locale,name,is_primary) SELECT id,'en','Haggai',TRUE FROM books WHERE code='HAG' ON DUPLICATE KEY UPDATE book_id=VALUES(book_id),is_primary=VALUES(is_primary);
INSERT INTO books (code,name,testament) VALUES ('ZEC','Zechariah','old') ON DUPLICATE KEY UPDATE name=VALUES(name), testament=VALUES(testament);
INSERT INTO canon_books (canon_id,book_id,position,chapter_count) SELECT c.id,b.id,45,14 FROM canons c JOIN books b ON b.code='ZEC' WHERE c.code='catholic-73' ON DUPLICATE KEY UPDATE position=VALUES(position),chapter_count=VALUES(chapter_count);
INSERT INTO book_names (book_id,locale,name,is_primary) SELECT id,'en','Zechariah',TRUE FROM books WHERE code='ZEC' ON DUPLICATE KEY UPDATE book_id=VALUES(book_id),is_primary=VALUES(is_primary);
INSERT INTO books (code,name,testament) VALUES ('MAL','Malachi','old') ON DUPLICATE KEY UPDATE name=VALUES(name), testament=VALUES(testament);
INSERT INTO canon_books (canon_id,book_id,position,chapter_count) SELECT c.id,b.id,46,4 FROM canons c JOIN books b ON b.code='MAL' WHERE c.code='catholic-73' ON DUPLICATE KEY UPDATE position=VALUES(position),chapter_count=VALUES(chapter_count);
INSERT INTO book_names (book_id,locale,name,is_primary) SELECT id,'en','Malachi',TRUE FROM books WHERE code='MAL' ON DUPLICATE KEY UPDATE book_id=VALUES(book_id),is_primary=VALUES(is_primary);
INSERT INTO books (code,name,testament) VALUES ('MAT','Matthew','new') ON DUPLICATE KEY UPDATE name=VALUES(name), testament=VALUES(testament);
INSERT INTO canon_books (canon_id,book_id,position,chapter_count) SELECT c.id,b.id,47,28 FROM canons c JOIN books b ON b.code='MAT' WHERE c.code='catholic-73' ON DUPLICATE KEY UPDATE position=VALUES(position),chapter_count=VALUES(chapter_count);
INSERT INTO book_names (book_id,locale,name,is_primary) SELECT id,'en','Matthew',TRUE FROM books WHERE code='MAT' ON DUPLICATE KEY UPDATE book_id=VALUES(book_id),is_primary=VALUES(is_primary);
INSERT INTO books (code,name,testament) VALUES ('MRK','Mark','new') ON DUPLICATE KEY UPDATE name=VALUES(name), testament=VALUES(testament);
INSERT INTO canon_books (canon_id,book_id,position,chapter_count) SELECT c.id,b.id,48,16 FROM canons c JOIN books b ON b.code='MRK' WHERE c.code='catholic-73' ON DUPLICATE KEY UPDATE position=VALUES(position),chapter_count=VALUES(chapter_count);
INSERT INTO book_names (book_id,locale,name,is_primary) SELECT id,'en','Mark',TRUE FROM books WHERE code='MRK' ON DUPLICATE KEY UPDATE book_id=VALUES(book_id),is_primary=VALUES(is_primary);
INSERT INTO books (code,name,testament) VALUES ('LUK','Luke','new') ON DUPLICATE KEY UPDATE name=VALUES(name), testament=VALUES(testament);
INSERT INTO canon_books (canon_id,book_id,position,chapter_count) SELECT c.id,b.id,49,24 FROM canons c JOIN books b ON b.code='LUK' WHERE c.code='catholic-73' ON DUPLICATE KEY UPDATE position=VALUES(position),chapter_count=VALUES(chapter_count);
INSERT INTO book_names (book_id,locale,name,is_primary) SELECT id,'en','Luke',TRUE FROM books WHERE code='LUK' ON DUPLICATE KEY UPDATE book_id=VALUES(book_id),is_primary=VALUES(is_primary);
INSERT INTO books (code,name,testament) VALUES ('JHN','John','new') ON DUPLICATE KEY UPDATE name=VALUES(name), testament=VALUES(testament);
INSERT INTO canon_books (canon_id,book_id,position,chapter_count) SELECT c.id,b.id,50,21 FROM canons c JOIN books b ON b.code='JHN' WHERE c.code='catholic-73' ON DUPLICATE KEY UPDATE position=VALUES(position),chapter_count=VALUES(chapter_count);
INSERT INTO book_names (book_id,locale,name,is_primary) SELECT id,'en','John',TRUE FROM books WHERE code='JHN' ON DUPLICATE KEY UPDATE book_id=VALUES(book_id),is_primary=VALUES(is_primary);
INSERT INTO books (code,name,testament) VALUES ('ACT','Acts','new') ON DUPLICATE KEY UPDATE name=VALUES(name), testament=VALUES(testament);
INSERT INTO canon_books (canon_id,book_id,position,chapter_count) SELECT c.id,b.id,51,28 FROM canons c JOIN books b ON b.code='ACT' WHERE c.code='catholic-73' ON DUPLICATE KEY UPDATE position=VALUES(position),chapter_count=VALUES(chapter_count);
INSERT INTO book_names (book_id,locale,name,is_primary) SELECT id,'en','Acts',TRUE FROM books WHERE code='ACT' ON DUPLICATE KEY UPDATE book_id=VALUES(book_id),is_primary=VALUES(is_primary);
INSERT INTO books (code,name,testament) VALUES ('ROM','Romans','new') ON DUPLICATE KEY UPDATE name=VALUES(name), testament=VALUES(testament);
INSERT INTO canon_books (canon_id,book_id,position,chapter_count) SELECT c.id,b.id,52,16 FROM canons c JOIN books b ON b.code='ROM' WHERE c.code='catholic-73' ON DUPLICATE KEY UPDATE position=VALUES(position),chapter_count=VALUES(chapter_count);
INSERT INTO book_names (book_id,locale,name,is_primary) SELECT id,'en','Romans',TRUE FROM books WHERE code='ROM' ON DUPLICATE KEY UPDATE book_id=VALUES(book_id),is_primary=VALUES(is_primary);
INSERT INTO books (code,name,testament) VALUES ('1CO','1 Corinthians','new') ON DUPLICATE KEY UPDATE name=VALUES(name), testament=VALUES(testament);
INSERT INTO canon_books (canon_id,book_id,position,chapter_count) SELECT c.id,b.id,53,16 FROM canons c JOIN books b ON b.code='1CO' WHERE c.code='catholic-73' ON DUPLICATE KEY UPDATE position=VALUES(position),chapter_count=VALUES(chapter_count);
INSERT INTO book_names (book_id,locale,name,is_primary) SELECT id,'en','1 Corinthians',TRUE FROM books WHERE code='1CO' ON DUPLICATE KEY UPDATE book_id=VALUES(book_id),is_primary=VALUES(is_primary);
INSERT INTO books (code,name,testament) VALUES ('2CO','2 Corinthians','new') ON DUPLICATE KEY UPDATE name=VALUES(name), testament=VALUES(testament);
INSERT INTO canon_books (canon_id,book_id,position,chapter_count) SELECT c.id,b.id,54,13 FROM canons c JOIN books b ON b.code='2CO' WHERE c.code='catholic-73' ON DUPLICATE KEY UPDATE position=VALUES(position),chapter_count=VALUES(chapter_count);
INSERT INTO book_names (book_id,locale,name,is_primary) SELECT id,'en','2 Corinthians',TRUE FROM books WHERE code='2CO' ON DUPLICATE KEY UPDATE book_id=VALUES(book_id),is_primary=VALUES(is_primary);
INSERT INTO books (code,name,testament) VALUES ('GAL','Galatians','new') ON DUPLICATE KEY UPDATE name=VALUES(name), testament=VALUES(testament);
INSERT INTO canon_books (canon_id,book_id,position,chapter_count) SELECT c.id,b.id,55,6 FROM canons c JOIN books b ON b.code='GAL' WHERE c.code='catholic-73' ON DUPLICATE KEY UPDATE position=VALUES(position),chapter_count=VALUES(chapter_count);
INSERT INTO book_names (book_id,locale,name,is_primary) SELECT id,'en','Galatians',TRUE FROM books WHERE code='GAL' ON DUPLICATE KEY UPDATE book_id=VALUES(book_id),is_primary=VALUES(is_primary);
INSERT INTO books (code,name,testament) VALUES ('EPH','Ephesians','new') ON DUPLICATE KEY UPDATE name=VALUES(name), testament=VALUES(testament);
INSERT INTO canon_books (canon_id,book_id,position,chapter_count) SELECT c.id,b.id,56,6 FROM canons c JOIN books b ON b.code='EPH' WHERE c.code='catholic-73' ON DUPLICATE KEY UPDATE position=VALUES(position),chapter_count=VALUES(chapter_count);
INSERT INTO book_names (book_id,locale,name,is_primary) SELECT id,'en','Ephesians',TRUE FROM books WHERE code='EPH' ON DUPLICATE KEY UPDATE book_id=VALUES(book_id),is_primary=VALUES(is_primary);
INSERT INTO books (code,name,testament) VALUES ('PHP','Philippians','new') ON DUPLICATE KEY UPDATE name=VALUES(name), testament=VALUES(testament);
INSERT INTO canon_books (canon_id,book_id,position,chapter_count) SELECT c.id,b.id,57,4 FROM canons c JOIN books b ON b.code='PHP' WHERE c.code='catholic-73' ON DUPLICATE KEY UPDATE position=VALUES(position),chapter_count=VALUES(chapter_count);
INSERT INTO book_names (book_id,locale,name,is_primary) SELECT id,'en','Philippians',TRUE FROM books WHERE code='PHP' ON DUPLICATE KEY UPDATE book_id=VALUES(book_id),is_primary=VALUES(is_primary);
INSERT INTO books (code,name,testament) VALUES ('COL','Colossians','new') ON DUPLICATE KEY UPDATE name=VALUES(name), testament=VALUES(testament);
INSERT INTO canon_books (canon_id,book_id,position,chapter_count) SELECT c.id,b.id,58,4 FROM canons c JOIN books b ON b.code='COL' WHERE c.code='catholic-73' ON DUPLICATE KEY UPDATE position=VALUES(position),chapter_count=VALUES(chapter_count);
INSERT INTO book_names (book_id,locale,name,is_primary) SELECT id,'en','Colossians',TRUE FROM books WHERE code='COL' ON DUPLICATE KEY UPDATE book_id=VALUES(book_id),is_primary=VALUES(is_primary);
INSERT INTO books (code,name,testament) VALUES ('1TH','1 Thessalonians','new') ON DUPLICATE KEY UPDATE name=VALUES(name), testament=VALUES(testament);
INSERT INTO canon_books (canon_id,book_id,position,chapter_count) SELECT c.id,b.id,59,5 FROM canons c JOIN books b ON b.code='1TH' WHERE c.code='catholic-73' ON DUPLICATE KEY UPDATE position=VALUES(position),chapter_count=VALUES(chapter_count);
INSERT INTO book_names (book_id,locale,name,is_primary) SELECT id,'en','1 Thessalonians',TRUE FROM books WHERE code='1TH' ON DUPLICATE KEY UPDATE book_id=VALUES(book_id),is_primary=VALUES(is_primary);
INSERT INTO books (code,name,testament) VALUES ('2TH','2 Thessalonians','new') ON DUPLICATE KEY UPDATE name=VALUES(name), testament=VALUES(testament);
INSERT INTO canon_books (canon_id,book_id,position,chapter_count) SELECT c.id,b.id,60,3 FROM canons c JOIN books b ON b.code='2TH' WHERE c.code='catholic-73' ON DUPLICATE KEY UPDATE position=VALUES(position),chapter_count=VALUES(chapter_count);
INSERT INTO book_names (book_id,locale,name,is_primary) SELECT id,'en','2 Thessalonians',TRUE FROM books WHERE code='2TH' ON DUPLICATE KEY UPDATE book_id=VALUES(book_id),is_primary=VALUES(is_primary);
INSERT INTO books (code,name,testament) VALUES ('1TI','1 Timothy','new') ON DUPLICATE KEY UPDATE name=VALUES(name), testament=VALUES(testament);
INSERT INTO canon_books (canon_id,book_id,position,chapter_count) SELECT c.id,b.id,61,6 FROM canons c JOIN books b ON b.code='1TI' WHERE c.code='catholic-73' ON DUPLICATE KEY UPDATE position=VALUES(position),chapter_count=VALUES(chapter_count);
INSERT INTO book_names (book_id,locale,name,is_primary) SELECT id,'en','1 Timothy',TRUE FROM books WHERE code='1TI' ON DUPLICATE KEY UPDATE book_id=VALUES(book_id),is_primary=VALUES(is_primary);
INSERT INTO books (code,name,testament) VALUES ('2TI','2 Timothy','new') ON DUPLICATE KEY UPDATE name=VALUES(name), testament=VALUES(testament);
INSERT INTO canon_books (canon_id,book_id,position,chapter_count) SELECT c.id,b.id,62,4 FROM canons c JOIN books b ON b.code='2TI' WHERE c.code='catholic-73' ON DUPLICATE KEY UPDATE position=VALUES(position),chapter_count=VALUES(chapter_count);
INSERT INTO book_names (book_id,locale,name,is_primary) SELECT id,'en','2 Timothy',TRUE FROM books WHERE code='2TI' ON DUPLICATE KEY UPDATE book_id=VALUES(book_id),is_primary=VALUES(is_primary);
INSERT INTO books (code,name,testament) VALUES ('TIT','Titus','new') ON DUPLICATE KEY UPDATE name=VALUES(name), testament=VALUES(testament);
INSERT INTO canon_books (canon_id,book_id,position,chapter_count) SELECT c.id,b.id,63,3 FROM canons c JOIN books b ON b.code='TIT' WHERE c.code='catholic-73' ON DUPLICATE KEY UPDATE position=VALUES(position),chapter_count=VALUES(chapter_count);
INSERT INTO book_names (book_id,locale,name,is_primary) SELECT id,'en','Titus',TRUE FROM books WHERE code='TIT' ON DUPLICATE KEY UPDATE book_id=VALUES(book_id),is_primary=VALUES(is_primary);
INSERT INTO books (code,name,testament) VALUES ('PHM','Philemon','new') ON DUPLICATE KEY UPDATE name=VALUES(name), testament=VALUES(testament);
INSERT INTO canon_books (canon_id,book_id,position,chapter_count) SELECT c.id,b.id,64,1 FROM canons c JOIN books b ON b.code='PHM' WHERE c.code='catholic-73' ON DUPLICATE KEY UPDATE position=VALUES(position),chapter_count=VALUES(chapter_count);
INSERT INTO book_names (book_id,locale,name,is_primary) SELECT id,'en','Philemon',TRUE FROM books WHERE code='PHM' ON DUPLICATE KEY UPDATE book_id=VALUES(book_id),is_primary=VALUES(is_primary);
INSERT INTO books (code,name,testament) VALUES ('HEB','Hebrews','new') ON DUPLICATE KEY UPDATE name=VALUES(name), testament=VALUES(testament);
INSERT INTO canon_books (canon_id,book_id,position,chapter_count) SELECT c.id,b.id,65,13 FROM canons c JOIN books b ON b.code='HEB' WHERE c.code='catholic-73' ON DUPLICATE KEY UPDATE position=VALUES(position),chapter_count=VALUES(chapter_count);
INSERT INTO book_names (book_id,locale,name,is_primary) SELECT id,'en','Hebrews',TRUE FROM books WHERE code='HEB' ON DUPLICATE KEY UPDATE book_id=VALUES(book_id),is_primary=VALUES(is_primary);
INSERT INTO books (code,name,testament) VALUES ('JAS','James','new') ON DUPLICATE KEY UPDATE name=VALUES(name), testament=VALUES(testament);
INSERT INTO canon_books (canon_id,book_id,position,chapter_count) SELECT c.id,b.id,66,5 FROM canons c JOIN books b ON b.code='JAS' WHERE c.code='catholic-73' ON DUPLICATE KEY UPDATE position=VALUES(position),chapter_count=VALUES(chapter_count);
INSERT INTO book_names (book_id,locale,name,is_primary) SELECT id,'en','James',TRUE FROM books WHERE code='JAS' ON DUPLICATE KEY UPDATE book_id=VALUES(book_id),is_primary=VALUES(is_primary);
INSERT INTO books (code,name,testament) VALUES ('1PE','1 Peter','new') ON DUPLICATE KEY UPDATE name=VALUES(name), testament=VALUES(testament);
INSERT INTO canon_books (canon_id,book_id,position,chapter_count) SELECT c.id,b.id,67,5 FROM canons c JOIN books b ON b.code='1PE' WHERE c.code='catholic-73' ON DUPLICATE KEY UPDATE position=VALUES(position),chapter_count=VALUES(chapter_count);
INSERT INTO book_names (book_id,locale,name,is_primary) SELECT id,'en','1 Peter',TRUE FROM books WHERE code='1PE' ON DUPLICATE KEY UPDATE book_id=VALUES(book_id),is_primary=VALUES(is_primary);
INSERT INTO books (code,name,testament) VALUES ('2PE','2 Peter','new') ON DUPLICATE KEY UPDATE name=VALUES(name), testament=VALUES(testament);
INSERT INTO canon_books (canon_id,book_id,position,chapter_count) SELECT c.id,b.id,68,3 FROM canons c JOIN books b ON b.code='2PE' WHERE c.code='catholic-73' ON DUPLICATE KEY UPDATE position=VALUES(position),chapter_count=VALUES(chapter_count);
INSERT INTO book_names (book_id,locale,name,is_primary) SELECT id,'en','2 Peter',TRUE FROM books WHERE code='2PE' ON DUPLICATE KEY UPDATE book_id=VALUES(book_id),is_primary=VALUES(is_primary);
INSERT INTO books (code,name,testament) VALUES ('1JN','1 John','new') ON DUPLICATE KEY UPDATE name=VALUES(name), testament=VALUES(testament);
INSERT INTO canon_books (canon_id,book_id,position,chapter_count) SELECT c.id,b.id,69,5 FROM canons c JOIN books b ON b.code='1JN' WHERE c.code='catholic-73' ON DUPLICATE KEY UPDATE position=VALUES(position),chapter_count=VALUES(chapter_count);
INSERT INTO book_names (book_id,locale,name,is_primary) SELECT id,'en','1 John',TRUE FROM books WHERE code='1JN' ON DUPLICATE KEY UPDATE book_id=VALUES(book_id),is_primary=VALUES(is_primary);
INSERT INTO books (code,name,testament) VALUES ('2JN','2 John','new') ON DUPLICATE KEY UPDATE name=VALUES(name), testament=VALUES(testament);
INSERT INTO canon_books (canon_id,book_id,position,chapter_count) SELECT c.id,b.id,70,1 FROM canons c JOIN books b ON b.code='2JN' WHERE c.code='catholic-73' ON DUPLICATE KEY UPDATE position=VALUES(position),chapter_count=VALUES(chapter_count);
INSERT INTO book_names (book_id,locale,name,is_primary) SELECT id,'en','2 John',TRUE FROM books WHERE code='2JN' ON DUPLICATE KEY UPDATE book_id=VALUES(book_id),is_primary=VALUES(is_primary);
INSERT INTO books (code,name,testament) VALUES ('3JN','3 John','new') ON DUPLICATE KEY UPDATE name=VALUES(name), testament=VALUES(testament);
INSERT INTO canon_books (canon_id,book_id,position,chapter_count) SELECT c.id,b.id,71,1 FROM canons c JOIN books b ON b.code='3JN' WHERE c.code='catholic-73' ON DUPLICATE KEY UPDATE position=VALUES(position),chapter_count=VALUES(chapter_count);
INSERT INTO book_names (book_id,locale,name,is_primary) SELECT id,'en','3 John',TRUE FROM books WHERE code='3JN' ON DUPLICATE KEY UPDATE book_id=VALUES(book_id),is_primary=VALUES(is_primary);
INSERT INTO books (code,name,testament) VALUES ('JUD','Jude','new') ON DUPLICATE KEY UPDATE name=VALUES(name), testament=VALUES(testament);
INSERT INTO canon_books (canon_id,book_id,position,chapter_count) SELECT c.id,b.id,72,1 FROM canons c JOIN books b ON b.code='JUD' WHERE c.code='catholic-73' ON DUPLICATE KEY UPDATE position=VALUES(position),chapter_count=VALUES(chapter_count);
INSERT INTO book_names (book_id,locale,name,is_primary) SELECT id,'en','Jude',TRUE FROM books WHERE code='JUD' ON DUPLICATE KEY UPDATE book_id=VALUES(book_id),is_primary=VALUES(is_primary);
INSERT INTO books (code,name,testament) VALUES ('REV','Revelation','new') ON DUPLICATE KEY UPDATE name=VALUES(name), testament=VALUES(testament);
INSERT INTO canon_books (canon_id,book_id,position,chapter_count) SELECT c.id,b.id,73,22 FROM canons c JOIN books b ON b.code='REV' WHERE c.code='catholic-73' ON DUPLICATE KEY UPDATE position=VALUES(position),chapter_count=VALUES(chapter_count);
INSERT INTO book_names (book_id,locale,name,is_primary) SELECT id,'en','Revelation',TRUE FROM books WHERE code='REV' ON DUPLICATE KEY UPDATE book_id=VALUES(book_id),is_primary=VALUES(is_primary);
INSERT INTO book_names (book_id,locale,name,is_primary) SELECT id,'en','Apocalypse',FALSE FROM books WHERE code='REV' ON DUPLICATE KEY UPDATE book_id=VALUES(book_id),is_primary=VALUES(is_primary);
INSERT INTO bible_providers (code,name,provider_type,is_active) VALUES ('local','Local licensed text','local',TRUE) ON DUPLICATE KEY UPDATE name=VALUES(name),is_active=TRUE;
INSERT INTO translations (provider_id,canon_id,code,name,language_code,copyright_notice,license_url,offline_allowed,is_active) SELECT p.id,c.id,'DRA1899','Douay-Rheims 1899 American Edition','en','Public domain. Source package: eBible.org engDRA.','https://ebible.org/Scriptures/details.php?id=engDRA',TRUE,FALSE FROM bible_providers p JOIN canons c ON c.code='catholic-73' WHERE p.code='local' ON DUPLICATE KEY UPDATE copyright_notice=VALUES(copyright_notice),license_url=VALUES(license_url),offline_allowed=TRUE;
INSERT INTO schema_migrations (version) VALUES ('002_catholic_canon') ON DUPLICATE KEY UPDATE version=VALUES(version);
COMMIT;
