-- The same correction as 011, for the King James and World English translations.
--
-- These two are affected far less than the Berean, but in the same way. What was
-- absorbed into the preceding verse here is:
--
--   KJV    the traditional epistle subscriptions ("Written from Rome unto the
--          Ephesians by Tychicus."), and the Hebrew letter names in Psalm 119
--   WEB-C  section headings in Daniel, and the Psalm 119 letter names
--
-- The Douay-Rheims is unaffected; its package carries no headings.
--
-- Safe to run more than once: each statement matches the exact damaged text.


-- ---------- King James Version ----------
SET @translation := (SELECT id FROM translations WHERE code = 'KJV');
SET @book := (SELECT id FROM books WHERE code = '1CO');
UPDATE bible_verses SET text = 'My love be with you all in Christ Jesus. Amen.' WHERE translation_id = @translation AND book_id = @book AND chapter = 16 AND verse = 24 AND verse_suffix = '' AND text = 'My love be with you all in Christ Jesus. Amen. The first epistle to the Corinthians was written from Philippi by Stephanas, and Fortunatus, and Achaicus, and Timotheus.';
SET @book := (SELECT id FROM books WHERE code = '1TH');
UPDATE bible_verses SET text = 'The grace of our Lord Jesus Christ be with you. Amen.' WHERE translation_id = @translation AND book_id = @book AND chapter = 5 AND verse = 28 AND verse_suffix = '' AND text = 'The grace of our Lord Jesus Christ be with you. Amen. The first epistle unto the Thessalonians was written from Athens.';
SET @book := (SELECT id FROM books WHERE code = '1TI');
UPDATE bible_verses SET text = 'Which some professing have erred concerning the faith. Grace be with thee. Amen.' WHERE translation_id = @translation AND book_id = @book AND chapter = 6 AND verse = 21 AND verse_suffix = '' AND text = 'Which some professing have erred concerning the faith. Grace be with thee. Amen. The first to Timothy was written from Laodicea, which is the chiefest city of Phrygia Pacatiana.';
SET @book := (SELECT id FROM books WHERE code = '2CO');
UPDATE bible_verses SET text = 'The grace of the Lord Jesus Christ, and the love of God, and the communion of the Holy Ghost, be with you all. Amen.' WHERE translation_id = @translation AND book_id = @book AND chapter = 13 AND verse = 14 AND verse_suffix = '' AND text = 'The grace of the Lord Jesus Christ, and the love of God, and the communion of the Holy Ghost, be with you all. Amen. The second epistle to the Corinthians was written from Philippi, a city of Macedonia, by Titus and Lucas.';
SET @book := (SELECT id FROM books WHERE code = '2TH');
UPDATE bible_verses SET text = 'The grace of our Lord Jesus Christ be with you all. Amen.' WHERE translation_id = @translation AND book_id = @book AND chapter = 3 AND verse = 18 AND verse_suffix = '' AND text = 'The grace of our Lord Jesus Christ be with you all. Amen. The second epistle to the Thessalonians was written from Athens.';
SET @book := (SELECT id FROM books WHERE code = '2TI');
UPDATE bible_verses SET text = 'The Lord Jesus Christ be with thy spirit. Grace be with you. Amen.' WHERE translation_id = @translation AND book_id = @book AND chapter = 4 AND verse = 22 AND verse_suffix = '' AND text = 'The Lord Jesus Christ be with thy spirit. Grace be with you. Amen. The second epistle unto Timotheus, ordained the first bishop of the church of the Ephesians, was written from Rome, when Paul was brought before Nero the second time.';
SET @book := (SELECT id FROM books WHERE code = 'COL');
UPDATE bible_verses SET text = 'The salutation by the hand of me Paul. Remember my bonds. Grace be with you. Amen.' WHERE translation_id = @translation AND book_id = @book AND chapter = 4 AND verse = 18 AND verse_suffix = '' AND text = 'The salutation by the hand of me Paul. Remember my bonds. Grace be with you. Amen. Written from Rome to the Colossians by Tychicus and Onesimus.';
SET @book := (SELECT id FROM books WHERE code = 'EPH');
UPDATE bible_verses SET text = 'Grace be with all them that love our Lord Jesus Christ in sincerity. Amen.' WHERE translation_id = @translation AND book_id = @book AND chapter = 6 AND verse = 24 AND verse_suffix = '' AND text = 'Grace be with all them that love our Lord Jesus Christ in sincerity. Amen. Written from Rome unto the Ephesians by Tychicus.';
SET @book := (SELECT id FROM books WHERE code = 'GAL');
UPDATE bible_verses SET text = 'Brethren, the grace of our Lord Jesus Christ be with your spirit. Amen.' WHERE translation_id = @translation AND book_id = @book AND chapter = 6 AND verse = 18 AND verse_suffix = '' AND text = 'Brethren, the grace of our Lord Jesus Christ be with your spirit. Amen. Unto the Galatians written from Rome.';
SET @book := (SELECT id FROM books WHERE code = 'HEB');
UPDATE bible_verses SET text = 'Grace be with you all. Amen.' WHERE translation_id = @translation AND book_id = @book AND chapter = 13 AND verse = 25 AND verse_suffix = '' AND text = 'Grace be with you all. Amen. Written to the Hebrews from Italy by Timothy.';
SET @book := (SELECT id FROM books WHERE code = 'PHM');
UPDATE bible_verses SET text = 'The grace of our Lord Jesus Christ be with your spirit. Amen.' WHERE translation_id = @translation AND book_id = @book AND chapter = 1 AND verse = 25 AND verse_suffix = '' AND text = 'The grace of our Lord Jesus Christ be with your spirit. Amen. Written from Rome to Philemon, by Onesimus, a servant.';
SET @book := (SELECT id FROM books WHERE code = 'PHP');
UPDATE bible_verses SET text = 'The grace of our Lord Jesus Christ be with you all. Amen.' WHERE translation_id = @translation AND book_id = @book AND chapter = 4 AND verse = 23 AND verse_suffix = '' AND text = 'The grace of our Lord Jesus Christ be with you all. Amen. It was written to the Philippians from Rome by Epaphroditus.';
SET @book := (SELECT id FROM books WHERE code = 'PSA');
UPDATE bible_verses SET text = 'I will keep thy statutes: O forsake me not utterly.' WHERE translation_id = @translation AND book_id = @book AND chapter = 119 AND verse = 8 AND verse_suffix = '' AND text = 'I will keep thy statutes: O forsake me not utterly. ב BETH.';
UPDATE bible_verses SET text = 'I will delight myself in thy statutes: I will not forget thy word.' WHERE translation_id = @translation AND book_id = @book AND chapter = 119 AND verse = 16 AND verse_suffix = '' AND text = 'I will delight myself in thy statutes: I will not forget thy word. ג GIMEL.';
UPDATE bible_verses SET text = 'Thy testimonies also are my delight and my counsellors.' WHERE translation_id = @translation AND book_id = @book AND chapter = 119 AND verse = 24 AND verse_suffix = '' AND text = 'Thy testimonies also are my delight and my counsellors. ד DALETH.';
UPDATE bible_verses SET text = 'I will run the way of thy commandments, when thou shalt enlarge my heart.' WHERE translation_id = @translation AND book_id = @book AND chapter = 119 AND verse = 32 AND verse_suffix = '' AND text = 'I will run the way of thy commandments, when thou shalt enlarge my heart. ה HE.';
UPDATE bible_verses SET text = 'Behold, I have longed after thy precepts: quicken me in thy righteousness.' WHERE translation_id = @translation AND book_id = @book AND chapter = 119 AND verse = 40 AND verse_suffix = '' AND text = 'Behold, I have longed after thy precepts: quicken me in thy righteousness. ו VAU.';
UPDATE bible_verses SET text = 'My hands also will I lift up unto thy commandments, which I have loved; and I will meditate in thy statutes.' WHERE translation_id = @translation AND book_id = @book AND chapter = 119 AND verse = 48 AND verse_suffix = '' AND text = 'My hands also will I lift up unto thy commandments, which I have loved; and I will meditate in thy statutes. ז ZAIN.';
UPDATE bible_verses SET text = 'This I had, because I kept thy precepts.' WHERE translation_id = @translation AND book_id = @book AND chapter = 119 AND verse = 56 AND verse_suffix = '' AND text = 'This I had, because I kept thy precepts. ח CHETH.';
UPDATE bible_verses SET text = 'The earth, O LORD, is full of thy mercy: teach me thy statutes.' WHERE translation_id = @translation AND book_id = @book AND chapter = 119 AND verse = 64 AND verse_suffix = '' AND text = 'The earth, O LORD, is full of thy mercy: teach me thy statutes. ט TETH.';
UPDATE bible_verses SET text = 'The law of thy mouth is better unto me than thousands of gold and silver.' WHERE translation_id = @translation AND book_id = @book AND chapter = 119 AND verse = 72 AND verse_suffix = '' AND text = 'The law of thy mouth is better unto me than thousands of gold and silver. י JOD.';
UPDATE bible_verses SET text = 'Let my heart be sound in thy statutes; that I be not ashamed.' WHERE translation_id = @translation AND book_id = @book AND chapter = 119 AND verse = 80 AND verse_suffix = '' AND text = 'Let my heart be sound in thy statutes; that I be not ashamed. כ CAPH.';
UPDATE bible_verses SET text = 'Quicken me after thy lovingkindness; so shall I keep the testimony of thy mouth.' WHERE translation_id = @translation AND book_id = @book AND chapter = 119 AND verse = 88 AND verse_suffix = '' AND text = 'Quicken me after thy lovingkindness; so shall I keep the testimony of thy mouth. ל LAMED.';
UPDATE bible_verses SET text = 'I have seen an end of all perfection: but thy commandment is exceeding broad.' WHERE translation_id = @translation AND book_id = @book AND chapter = 119 AND verse = 96 AND verse_suffix = '' AND text = 'I have seen an end of all perfection: but thy commandment is exceeding broad. מ MEM.';
UPDATE bible_verses SET text = 'Through thy precepts I get understanding: therefore I hate every false way.' WHERE translation_id = @translation AND book_id = @book AND chapter = 119 AND verse = 104 AND verse_suffix = '' AND text = 'Through thy precepts I get understanding: therefore I hate every false way. נ NUN.';
UPDATE bible_verses SET text = 'I have inclined mine heart to perform thy statutes alway, even unto the end.' WHERE translation_id = @translation AND book_id = @book AND chapter = 119 AND verse = 112 AND verse_suffix = '' AND text = 'I have inclined mine heart to perform thy statutes alway, even unto the end. ס SAMECH.';
UPDATE bible_verses SET text = 'My flesh trembleth for fear of thee; and I am afraid of thy judgments.' WHERE translation_id = @translation AND book_id = @book AND chapter = 119 AND verse = 120 AND verse_suffix = '' AND text = 'My flesh trembleth for fear of thee; and I am afraid of thy judgments. ע AIN.';
UPDATE bible_verses SET text = 'Therefore I esteem all thy precepts concerning all things to be right; and I hate every false way.' WHERE translation_id = @translation AND book_id = @book AND chapter = 119 AND verse = 128 AND verse_suffix = '' AND text = 'Therefore I esteem all thy precepts concerning all things to be right; and I hate every false way. פ PE.';
UPDATE bible_verses SET text = 'Rivers of waters run down mine eyes, because they keep not thy law.' WHERE translation_id = @translation AND book_id = @book AND chapter = 119 AND verse = 136 AND verse_suffix = '' AND text = 'Rivers of waters run down mine eyes, because they keep not thy law. צ TZADDI.';
UPDATE bible_verses SET text = 'The righteousness of thy testimonies is everlasting: give me understanding, and I shall live.' WHERE translation_id = @translation AND book_id = @book AND chapter = 119 AND verse = 144 AND verse_suffix = '' AND text = 'The righteousness of thy testimonies is everlasting: give me understanding, and I shall live. ק KOPH.';
UPDATE bible_verses SET text = 'Concerning thy testimonies, I have known of old that thou hast founded them for ever.' WHERE translation_id = @translation AND book_id = @book AND chapter = 119 AND verse = 152 AND verse_suffix = '' AND text = 'Concerning thy testimonies, I have known of old that thou hast founded them for ever. ר RESH.';
UPDATE bible_verses SET text = 'Thy word is true from the beginning: and every one of thy righteous judgments endureth for ever.' WHERE translation_id = @translation AND book_id = @book AND chapter = 119 AND verse = 160 AND verse_suffix = '' AND text = 'Thy word is true from the beginning: and every one of thy righteous judgments endureth for ever. ש SCHIN.';
UPDATE bible_verses SET text = 'I have kept thy precepts and thy testimonies: for all my ways are before thee.' WHERE translation_id = @translation AND book_id = @book AND chapter = 119 AND verse = 168 AND verse_suffix = '' AND text = 'I have kept thy precepts and thy testimonies: for all my ways are before thee. ת TAU.';
SET @book := (SELECT id FROM books WHERE code = 'ROM');
UPDATE bible_verses SET text = 'To God only wise, be glory through Jesus Christ for ever. Amen.' WHERE translation_id = @translation AND book_id = @book AND chapter = 16 AND verse = 27 AND verse_suffix = '' AND text = 'To God only wise, be glory through Jesus Christ for ever. Amen. Written to the Romans from Corinthus, and sent by Phebe servant of the church at Cenchrea.';
SET @book := (SELECT id FROM books WHERE code = 'TIT');
UPDATE bible_verses SET text = 'All that are with me salute thee. Greet them that love us in the faith. Grace be with you all. Amen.' WHERE translation_id = @translation AND book_id = @book AND chapter = 3 AND verse = 15 AND verse_suffix = '' AND text = 'All that are with me salute thee. Greet them that love us in the faith. Grace be with you all. Amen. It was written to Titus, ordained the first bishop of the church of the Cretians, from Nicopolis of Macedonia.';

-- ---------- World English Bible, Catholic Edition ----------
SET @translation := (SELECT id FROM translations WHERE code = 'WEB-C');
SET @book := (SELECT id FROM books WHERE code = 'DAN');
UPDATE bible_verses SET text = 'These three men, Shadrach, Meshach, and Abednego, fell down bound into the middle of the burning fiery furnace.' WHERE translation_id = @translation AND book_id = @book AND chapter = 3 AND verse = 23 AND verse_suffix = '' AND text = 'These three men, Shadrach, Meshach, and Abednego, fell down bound into the middle of the burning fiery furnace. THE SONG OF THE THREE HOLY CHILDREN';
UPDATE bible_verses SET text = 'O all you who worship the Lord, bless the God of gods, praise him, and give him thanks; for his mercy is forever!”' WHERE translation_id = @translation AND book_id = @book AND chapter = 3 AND verse = 90 AND verse_suffix = '' AND text = 'O all you who worship the Lord, bless the God of gods, praise him, and give him thanks; for his mercy is forever!” Deliverance from the Furnace';
SET @book := (SELECT id FROM books WHERE code = 'PSA');
UPDATE bible_verses SET text = 'I will observe your statutes. Don’t utterly forsake me.' WHERE translation_id = @translation AND book_id = @book AND chapter = 119 AND verse = 8 AND verse_suffix = '' AND text = 'I will observe your statutes. Don’t utterly forsake me. BETH';
UPDATE bible_verses SET text = 'I will delight myself in your statutes. I will not forget your word.' WHERE translation_id = @translation AND book_id = @book AND chapter = 119 AND verse = 16 AND verse_suffix = '' AND text = 'I will delight myself in your statutes. I will not forget your word. GIMEL';
UPDATE bible_verses SET text = 'Indeed your statutes are my delight, and my counselors.' WHERE translation_id = @translation AND book_id = @book AND chapter = 119 AND verse = 24 AND verse_suffix = '' AND text = 'Indeed your statutes are my delight, and my counselors. DALETH';
UPDATE bible_verses SET text = 'I run in the path of your commandments, for you have set my heart free.' WHERE translation_id = @translation AND book_id = @book AND chapter = 119 AND verse = 32 AND verse_suffix = '' AND text = 'I run in the path of your commandments, for you have set my heart free. HE';
UPDATE bible_verses SET text = 'Behold, I long for your precepts! Revive me in your righteousness.' WHERE translation_id = @translation AND book_id = @book AND chapter = 119 AND verse = 40 AND verse_suffix = '' AND text = 'Behold, I long for your precepts! Revive me in your righteousness. VAV';
UPDATE bible_verses SET text = 'I reach out my hands for your commandments, which I love. I will meditate on your statutes.' WHERE translation_id = @translation AND book_id = @book AND chapter = 119 AND verse = 48 AND verse_suffix = '' AND text = 'I reach out my hands for your commandments, which I love. I will meditate on your statutes. ZAYIN';
UPDATE bible_verses SET text = 'This is my way, that I keep your precepts.' WHERE translation_id = @translation AND book_id = @book AND chapter = 119 AND verse = 56 AND verse_suffix = '' AND text = 'This is my way, that I keep your precepts. HETH';
UPDATE bible_verses SET text = 'The earth is full of your loving kindness, LORD. Teach me your statutes.' WHERE translation_id = @translation AND book_id = @book AND chapter = 119 AND verse = 64 AND verse_suffix = '' AND text = 'The earth is full of your loving kindness, LORD. Teach me your statutes. TETH';
UPDATE bible_verses SET text = 'The law of your mouth is better to me than thousands of pieces of gold and silver.' WHERE translation_id = @translation AND book_id = @book AND chapter = 119 AND verse = 72 AND verse_suffix = '' AND text = 'The law of your mouth is better to me than thousands of pieces of gold and silver. YODH';
UPDATE bible_verses SET text = 'Let my heart be blameless toward your decrees, that I may not be disappointed.' WHERE translation_id = @translation AND book_id = @book AND chapter = 119 AND verse = 80 AND verse_suffix = '' AND text = 'Let my heart be blameless toward your decrees, that I may not be disappointed. KAPF';
UPDATE bible_verses SET text = 'Preserve my life according to your loving kindness, so I will obey the statutes of your mouth.' WHERE translation_id = @translation AND book_id = @book AND chapter = 119 AND verse = 88 AND verse_suffix = '' AND text = 'Preserve my life according to your loving kindness, so I will obey the statutes of your mouth. LAMEDH';
UPDATE bible_verses SET text = 'I have seen a limit to all perfection, but your commands are boundless.' WHERE translation_id = @translation AND book_id = @book AND chapter = 119 AND verse = 96 AND verse_suffix = '' AND text = 'I have seen a limit to all perfection, but your commands are boundless. MEM';
UPDATE bible_verses SET text = 'Through your precepts, I get understanding; therefore I hate every false way.' WHERE translation_id = @translation AND book_id = @book AND chapter = 119 AND verse = 104 AND verse_suffix = '' AND text = 'Through your precepts, I get understanding; therefore I hate every false way. NUN';
UPDATE bible_verses SET text = 'I have set my heart to perform your statutes forever, even to the end.' WHERE translation_id = @translation AND book_id = @book AND chapter = 119 AND verse = 112 AND verse_suffix = '' AND text = 'I have set my heart to perform your statutes forever, even to the end. SAMEKH';
UPDATE bible_verses SET text = 'My flesh trembles for fear of you. I am afraid of your judgments.' WHERE translation_id = @translation AND book_id = @book AND chapter = 119 AND verse = 120 AND verse_suffix = '' AND text = 'My flesh trembles for fear of you. I am afraid of your judgments. AYIN';
UPDATE bible_verses SET text = 'Therefore I consider all of your precepts to be right. I hate every false way.' WHERE translation_id = @translation AND book_id = @book AND chapter = 119 AND verse = 128 AND verse_suffix = '' AND text = 'Therefore I consider all of your precepts to be right. I hate every false way. PE';
UPDATE bible_verses SET text = 'Streams of tears run down my eyes, because they don’t observe your law.' WHERE translation_id = @translation AND book_id = @book AND chapter = 119 AND verse = 136 AND verse_suffix = '' AND text = 'Streams of tears run down my eyes, because they don’t observe your law. TZADHE';
UPDATE bible_verses SET text = 'Your testimonies are righteous forever. Give me understanding, that I may live.' WHERE translation_id = @translation AND book_id = @book AND chapter = 119 AND verse = 144 AND verse_suffix = '' AND text = 'Your testimonies are righteous forever. Give me understanding, that I may live. QOPH';
UPDATE bible_verses SET text = 'Of old I have known from your testimonies, that you have founded them forever.' WHERE translation_id = @translation AND book_id = @book AND chapter = 119 AND verse = 152 AND verse_suffix = '' AND text = 'Of old I have known from your testimonies, that you have founded them forever. RESH';
UPDATE bible_verses SET text = 'All of your words are truth. Every one of your righteous ordinances endures forever.' WHERE translation_id = @translation AND book_id = @book AND chapter = 119 AND verse = 160 AND verse_suffix = '' AND text = 'All of your words are truth. Every one of your righteous ordinances endures forever. SIN AND SHIN';
UPDATE bible_verses SET text = 'I have obeyed your precepts and your testimonies, for all my ways are before you.' WHERE translation_id = @translation AND book_id = @book AND chapter = 119 AND verse = 168 AND verse_suffix = '' AND text = 'I have obeyed your precepts and your testimonies, for all my ways are before you. TAV';
SET @book := (SELECT id FROM books WHERE code = 'SNG');
UPDATE bible_verses SET text = 'The Song of songs, which is Solomon’s.' WHERE translation_id = @translation AND book_id = @book AND chapter = 1 AND verse = 1 AND verse_suffix = '' AND text = 'The Song of songs, which is Solomon’s. Beloved';
UPDATE bible_verses SET text = 'Take me away with you. Let’s hurry. The king has brought me into his rooms. We will be glad and rejoice in you. We will praise your love more than wine! They are right to love you.' WHERE translation_id = @translation AND book_id = @book AND chapter = 1 AND verse = 4 AND verse_suffix = '' AND text = 'Take me away with you. Let’s hurry. The king has brought me into his rooms. Friends We will be glad and rejoice in you. We will praise your love more than wine! Beloved They are right to love you.';
UPDATE bible_verses SET text = 'Tell me, you whom my soul loves, where you graze your flock, where you rest them at noon; for why should I be as one who is veiled beside the flocks of your companions?' WHERE translation_id = @translation AND book_id = @book AND chapter = 1 AND verse = 7 AND verse_suffix = '' AND text = 'Tell me, you whom my soul loves, where you graze your flock, where you rest them at noon; for why should I be as one who is veiled beside the flocks of your companions? Lover';
UPDATE bible_verses SET text = 'Your cheeks are beautiful with earrings, your neck with strings of jewels.' WHERE translation_id = @translation AND book_id = @book AND chapter = 1 AND verse = 10 AND verse_suffix = '' AND text = 'Your cheeks are beautiful with earrings, your neck with strings of jewels. Friends';
UPDATE bible_verses SET text = 'We will make you earrings of gold, with studs of silver.' WHERE translation_id = @translation AND book_id = @book AND chapter = 1 AND verse = 11 AND verse_suffix = '' AND text = 'We will make you earrings of gold, with studs of silver. Beloved';
UPDATE bible_verses SET text = 'My beloved is to me a cluster of henna blossoms from the vineyards of En Gedi.' WHERE translation_id = @translation AND book_id = @book AND chapter = 1 AND verse = 14 AND verse_suffix = '' AND text = 'My beloved is to me a cluster of henna blossoms from the vineyards of En Gedi. Lover';
UPDATE bible_verses SET text = 'Behold, you are beautiful, my love. Behold, you are beautiful. Your eyes are like doves.' WHERE translation_id = @translation AND book_id = @book AND chapter = 1 AND verse = 15 AND verse_suffix = '' AND text = 'Behold, you are beautiful, my love. Behold, you are beautiful. Your eyes are like doves. Beloved';
UPDATE bible_verses SET text = 'Behold, you are beautiful, my beloved, yes, pleasant; and our couch is verdant.' WHERE translation_id = @translation AND book_id = @book AND chapter = 1 AND verse = 16 AND verse_suffix = '' AND text = 'Behold, you are beautiful, my beloved, yes, pleasant; and our couch is verdant. Lover';
UPDATE bible_verses SET text = 'I am a rose of Sharon, a lily of the valleys.' WHERE translation_id = @translation AND book_id = @book AND chapter = 2 AND verse = 1 AND verse_suffix = '' AND text = 'I am a rose of Sharon, a lily of the valleys. Lover';
UPDATE bible_verses SET text = 'As a lily among thorns, so is my love among the daughters.' WHERE translation_id = @translation AND book_id = @book AND chapter = 2 AND verse = 2 AND verse_suffix = '' AND text = 'As a lily among thorns, so is my love among the daughters. Beloved';
UPDATE bible_verses SET text = 'The fig tree ripens her green figs. The vines are in blossom. They give out their fragrance. Arise, my love, my beautiful one, and come away.”' WHERE translation_id = @translation AND book_id = @book AND chapter = 2 AND verse = 13 AND verse_suffix = '' AND text = 'The fig tree ripens her green figs. The vines are in blossom. They give out their fragrance. Arise, my love, my beautiful one, and come away.” Lover';
UPDATE bible_verses SET text = 'Catch for us the foxes, the little foxes that plunder the vineyards; for our vineyards are in blossom.' WHERE translation_id = @translation AND book_id = @book AND chapter = 2 AND verse = 15 AND verse_suffix = '' AND text = 'Catch for us the foxes, the little foxes that plunder the vineyards; for our vineyards are in blossom. Beloved';
UPDATE bible_verses SET text = 'a fountain of gardens, a well of living waters, flowing streams from Lebanon.' WHERE translation_id = @translation AND book_id = @book AND chapter = 4 AND verse = 15 AND verse_suffix = '' AND text = 'a fountain of gardens, a well of living waters, flowing streams from Lebanon. Beloved';
UPDATE bible_verses SET text = 'I have come into my garden, my sister, my bride. I have gathered my myrrh with my spice; I have eaten my honeycomb with my honey; I have drunk my wine with my milk. Eat, friends! Drink, yes, drink abundantly, beloved.' WHERE translation_id = @translation AND book_id = @book AND chapter = 5 AND verse = 1 AND verse_suffix = '' AND text = 'I have come into my garden, my sister, my bride. I have gathered my myrrh with my spice; I have eaten my honeycomb with my honey; I have drunk my wine with my milk. Friends Eat, friends! Drink, yes, drink abundantly, beloved. Beloved';
UPDATE bible_verses SET text = 'I adjure you, daughters of Jerusalem, If you find my beloved, that you tell him that I am faint with love.' WHERE translation_id = @translation AND book_id = @book AND chapter = 5 AND verse = 8 AND verse_suffix = '' AND text = 'I adjure you, daughters of Jerusalem, If you find my beloved, that you tell him that I am faint with love. Friends';
UPDATE bible_verses SET text = 'How is your beloved better than another beloved, you fairest among women? How is your beloved better than another beloved, that you do so adjure us?' WHERE translation_id = @translation AND book_id = @book AND chapter = 5 AND verse = 9 AND verse_suffix = '' AND text = 'How is your beloved better than another beloved, you fairest among women? How is your beloved better than another beloved, that you do so adjure us? Beloved';
UPDATE bible_verses SET text = 'Where has your beloved gone, you fairest among women? Where has your beloved turned, that we may seek him with you?' WHERE translation_id = @translation AND book_id = @book AND chapter = 6 AND verse = 1 AND verse_suffix = '' AND text = 'Where has your beloved gone, you fairest among women? Where has your beloved turned, that we may seek him with you? Beloved';
UPDATE bible_verses SET text = 'I am my beloved’s, and my beloved is mine. He browses among the lilies.' WHERE translation_id = @translation AND book_id = @book AND chapter = 6 AND verse = 3 AND verse_suffix = '' AND text = 'I am my beloved’s, and my beloved is mine. He browses among the lilies. Lover';
UPDATE bible_verses SET text = 'Without realizing it, my desire set me with my royal people’s chariots.' WHERE translation_id = @translation AND book_id = @book AND chapter = 6 AND verse = 12 AND verse_suffix = '' AND text = 'Without realizing it, my desire set me with my royal people’s chariots. Friends';
UPDATE bible_verses SET text = 'Return, return, Shulammite! Return, return, that we may gaze at you. Why do you desire to gaze at the Shulammite, as at the dance of Mahanaim?' WHERE translation_id = @translation AND book_id = @book AND chapter = 6 AND verse = 13 AND verse_suffix = '' AND text = 'Return, return, Shulammite! Return, return, that we may gaze at you. Lover Why do you desire to gaze at the Shulammite, as at the dance of Mahanaim?';
UPDATE bible_verses SET text = 'Your mouth is like the best wine, that goes down smoothly for my beloved, gliding through the lips of those who are asleep.' WHERE translation_id = @translation AND book_id = @book AND chapter = 7 AND verse = 9 AND verse_suffix = '' AND text = 'Your mouth is like the best wine, that goes down smoothly for my beloved, gliding through the lips of those who are asleep. Beloved';
UPDATE bible_verses SET text = 'I adjure you, daughters of Jerusalem, that you not stir up, nor awaken love, until it so desires.' WHERE translation_id = @translation AND book_id = @book AND chapter = 8 AND verse = 4 AND verse_suffix = '' AND text = 'I adjure you, daughters of Jerusalem, that you not stir up, nor awaken love, until it so desires. Friends';
UPDATE bible_verses SET text = 'Who is this who comes up from the wilderness, leaning on her beloved? Under the apple tree I awakened you. There your mother conceived you. There she was in labor and bore you.' WHERE translation_id = @translation AND book_id = @book AND chapter = 8 AND verse = 5 AND verse_suffix = '' AND text = 'Who is this who comes up from the wilderness, leaning on her beloved? Beloved Under the apple tree I awakened you. There your mother conceived you. There she was in labor and bore you.';
UPDATE bible_verses SET text = 'Many waters can’t quench love, neither can floods drown it. If a man would give all the wealth of his house for love, he would be utterly scorned.' WHERE translation_id = @translation AND book_id = @book AND chapter = 8 AND verse = 7 AND verse_suffix = '' AND text = 'Many waters can’t quench love, neither can floods drown it. If a man would give all the wealth of his house for love, he would be utterly scorned. Brothers';
UPDATE bible_verses SET text = 'If she is a wall, we will build on her a turret of silver. If she is a door, we will enclose her with boards of cedar.' WHERE translation_id = @translation AND book_id = @book AND chapter = 8 AND verse = 9 AND verse_suffix = '' AND text = 'If she is a wall, we will build on her a turret of silver. If she is a door, we will enclose her with boards of cedar. Beloved';
UPDATE bible_verses SET text = 'My own vineyard is before me. The thousand are for you, Solomon, two hundred for those who tend its fruit.' WHERE translation_id = @translation AND book_id = @book AND chapter = 8 AND verse = 12 AND verse_suffix = '' AND text = 'My own vineyard is before me. The thousand are for you, Solomon, two hundred for those who tend its fruit. Lover';
UPDATE bible_verses SET text = 'You who dwell in the gardens, with friends in attendance, let me hear your voice!' WHERE translation_id = @translation AND book_id = @book AND chapter = 8 AND verse = 13 AND verse_suffix = '' AND text = 'You who dwell in the gardens, with friends in attendance, let me hear your voice! Beloved';
